# Generated by Django 4.1.7 on 2023-12-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rating_author_rating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='author',
            field=models.CharField(default='User', max_length=200),
        ),
    ]
