# Generated by Django 4.1.7 on 2023-12-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rating_anonymous_alter_rating_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='summary',
            field=models.CharField(default='summary', max_length=300),
        ),
    ]
