# Generated by Django 4.1.7 on 2023-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rating_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='summary',
        ),
        migrations.AddField(
            model_name='rating',
            name='summary_word1',
            field=models.CharField(default='word1', max_length=300),
        ),
        migrations.AddField(
            model_name='rating',
            name='summary_word2',
            field=models.CharField(default='word2', max_length=300),
        ),
        migrations.AddField(
            model_name='rating',
            name='summary_word3',
            field=models.CharField(default='word3', max_length=300),
        ),
    ]
